use crate::detour::Detour;
use crate::error::Result;
use crate::{Function, HookableWith};
use core::marker::PhantomData;

/// A type-safe detour.
///
/// Due to being generated by a macro, the `GenericDetour::call` method is not
/// exposed in the documentation. It accepts the same arguments as `T`, and
/// shares its result type:
///
/// ```ignore
/// /// Calls the original function regardless of whether it's hooked or not.
/// fn call(&self, T::Arguments) -> T::Output
/// ```
///
/// If `T` is an `unsafe` function, `call` is `unsafe` as well.
///
/// # Example
///
/// ```rust
/// # use detour::Result;
/// use detour::GenericDetour;
///
/// #[inline(never)]
/// fn add5(val: i32) -> i32 {
///   val + 5
/// }
///
/// #[inline(never)]
/// fn add10(val: i32) -> i32 {
///   val + 10
/// }
///
/// # fn main() -> Result<()> {
/// let mut hook = unsafe { GenericDetour::<fn(i32) -> i32>::new(add5, add10)? };
///
/// assert_eq!(add5(5), 10);
/// assert_eq!(hook.call(5), 10);
///
/// unsafe { hook.enable()? };
///
/// assert_eq!(add5(5), 15);
/// assert_eq!(hook.call(5), 10);
///
/// unsafe { hook.disable()? };
///
/// assert_eq!(add5(5), 10);
/// # Ok(())
/// # }
/// ```
pub struct GenericDetour<T: Function> {
  phantom: PhantomData<T>,
  detour: Detour,
}

impl<T: Function> GenericDetour<T> {
  /// Create a new hook given a target function and a compatible detour
  /// function.
  ///
  /// # Safety
  ///
  /// The target must be a function (e.g. not a Rust-ABI function that has
  /// been inlined into all of its callers) with the declared signature.
  pub unsafe fn new<D>(target: T, detour: D) -> Result<Self>
  where
    T: HookableWith<D>,
    D: Function,
  {
    // SAFETY: The signatures are compatible, as asserted by `HookableWith`.
    unsafe { Detour::new(target.to_ptr(), detour.to_ptr()) }.map(|detour| GenericDetour {
      phantom: PhantomData,
      detour,
    })
  }

  /// Enables the detour.
  ///
  /// # Safety
  ///
  /// The target must not be executing its prolog (i.e. the patched
  /// instructions) on another thread whilst the detour is being enabled.
  pub unsafe fn enable(&self) -> Result<()> {
    // SAFETY: Forwarded from the caller.
    unsafe { self.detour.enable() }
  }

  /// Disables the detour.
  ///
  /// # Safety
  ///
  /// See [`GenericDetour::enable`].
  pub unsafe fn disable(&self) -> Result<()> {
    // SAFETY: Forwarded from the caller.
    unsafe { self.detour.disable() }
  }

  /// Returns whether the detour is enabled or not.
  pub fn is_enabled(&self) -> bool {
    self.detour.is_enabled()
  }

  /// Returns a pointer to the generated trampoline.
  pub(crate) fn trampoline(&self) -> *const () {
    self.detour.trampoline()
  }
}

impl<T: Function> core::fmt::Debug for GenericDetour<T> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    f.debug_tuple("GenericDetour").field(&self.detour).finish()
  }
}
