use crate::error::{Error, Result};
use crate::{Function, GenericDetour};
use std::sync::{Arc, OnceLock, PoisonError, RwLock};

/// A type-safe static detour.
///
/// Due to being generated by a macro, several methods are not exposed in the
/// documentation. They accept the argument and result types of `T`:
///
/// ```ignore
/// /// Creates the detour of `target`, redirected to `closure`.
/// ///
/// /// This can only be called once; subsequent calls fail with
/// /// `Error::AlreadyInitialized`. It returns `&self` to allow chaining.
/// unsafe fn initialize<D>(&self, target: T, closure: D) -> Result<&Self>
/// where D: Fn(T::Arguments...) -> T::Output + Send + Sync + 'static;
///
/// /// Changes the detour, regardless of whether the hook is enabled or not.
/// fn set_detour<D>(&self, closure: D)
/// where D: Fn(T::Arguments...) -> T::Output + Send + Sync + 'static;
///
/// /// Calls the original function regardless of whether it's hooked or not.
/// ///
/// /// Panics if called when the static detour has not yet been initialized.
/// fn call(&self, T::Arguments...) -> T::Output
/// ```
///
/// If `T` is an `unsafe` function, `call` is `unsafe` as well.
///
/// To define a static detour, use the [`static_detour`](crate::static_detour)
/// macro.
///
/// # Example
///
/// ```rust
/// use std::error::Error;
/// use detour::static_detour;
///
/// static_detour! {
///   static Test: fn(i32) -> i32;
/// }
///
/// #[inline(never)]
/// fn add5(val: i32) -> i32 {
///   val + 5
/// }
///
/// fn add10(val: i32) -> i32 {
///   val + 10
/// }
///
/// fn main() -> Result<(), Box<dyn Error>> {
///   // Replace the 'add5' function with 'add10' (can also be a closure)
///   unsafe { Test.initialize(add5, add10)? };
///
///   assert_eq!(add5(1), 6);
///   assert_eq!(Test.call(1), 6);
///
///   unsafe { Test.enable()? };
///
///   // The original function is detoured to 'add10'
///   assert_eq!(add5(1), 11);
///
///   // The original function can still be invoked using 'call'
///   assert_eq!(Test.call(1), 6);
///
///   // It is also possible to change the detour whilst hooked
///   Test.set_detour(|val| val - 5);
///   assert_eq!(add5(5), 0);
///
///   unsafe { Test.disable()? };
///
///   assert_eq!(add5(1), 6);
///   Ok(())
/// }
/// ```
pub struct StaticDetour<T: Function> {
  closure: RwLock<Option<Arc<T::Closure>>>,
  detour: OnceLock<GenericDetour<T>>,
  ffi: T,
}

impl<T: Function> StaticDetour<T> {
  /// Create a new static detour.
  #[doc(hidden)]
  pub const fn __new(ffi: T) -> Self {
    StaticDetour {
      closure: RwLock::new(None),
      detour: OnceLock::new(),
      ffi,
    }
  }

  /// Creates the detour; see `initialize`.
  pub(crate) unsafe fn initialize_shared(
    &self,
    target: T,
    closure: Arc<T::Closure>,
  ) -> Result<&Self> {
    if self.detour.get().is_some() {
      return Err(Error::AlreadyInitialized);
    }

    // SAFETY: The target is compatible with the generated FFI function.
    let detour = unsafe { GenericDetour::new(target, self.ffi)? };

    // Another thread may have raced to initialize the detour
    self
      .detour
      .set(detour)
      .map_err(|_| Error::AlreadyInitialized)?;
    self.set_detour_shared(closure);
    Ok(self)
  }

  /// Enables the detour.
  ///
  /// # Safety
  ///
  /// See [`GenericDetour::enable`].
  pub unsafe fn enable(&self) -> Result<()> {
    let detour = self.detour.get().ok_or(Error::NotInitialized)?;
    // SAFETY: Forwarded from the caller.
    unsafe { detour.enable() }
  }

  /// Disables the detour.
  ///
  /// # Safety
  ///
  /// See [`GenericDetour::enable`].
  pub unsafe fn disable(&self) -> Result<()> {
    let detour = self.detour.get().ok_or(Error::NotInitialized)?;
    // SAFETY: Forwarded from the caller.
    unsafe { detour.disable() }
  }

  /// Returns whether the detour is enabled or not.
  pub fn is_enabled(&self) -> bool {
    self.detour.get().is_some_and(GenericDetour::is_enabled)
  }

  /// Replaces the detour closure; see `set_detour`.
  pub(crate) fn set_detour_shared(&self, closure: Arc<T::Closure>) {
    let mut current = self.closure.write().unwrap_or_else(PoisonError::into_inner);
    let previous = current.replace(closure);
    drop(current);

    // Dropped outside of the lock, in case the closure's destructor calls the
    // detoured function.
    drop(previous);
  }

  /// Returns the active detour closure.
  #[doc(hidden)]
  pub fn __detour(&self) -> Arc<T::Closure> {
    self
      .closure
      .read()
      .unwrap_or_else(PoisonError::into_inner)
      .clone()
      .expect("static detour closure is not initialized")
  }

  /// Returns a pointer to the generated trampoline.
  pub(crate) fn trampoline(&self) -> *const () {
    self
      .detour
      .get()
      .expect("static detour is not initialized")
      .trampoline()
  }
}

impl<T: Function> std::fmt::Debug for StaticDetour<T> {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.debug_struct("StaticDetour")
      .field("detour", &self.detour.get())
      .finish_non_exhaustive()
  }
}
