//! The state of static detours, and the handles generated by `static_detour!`.

use crate::error::{Error, Result};
use crate::hook::Hook;
use crate::sync::Mutex;
use alloc::boxed::Box;
use alloc::vec::Vec;
use core::marker::PhantomData;
use core::sync::atomic::{AtomicPtr, AtomicUsize, Ordering};
use core::{fmt, mem, ptr};

/// The state of a static detour, defined by [`static_detour!`].
///
/// `F` is the function pointer type, and `C` the (unsized) closure type of
/// the detour. It is an implementation detail of the generated handles.
///
/// [`static_detour!`]: crate::static_detour
#[doc(hidden)]
pub struct StaticDetour<F, C: ?Sized> {
  // The active closure, or null if not yet initialized.
  closure: AtomicPtr<Box<C>>,
  // The number of calls currently executing a closure.
  active_calls: AtomicUsize,
  // Replaced closures, which may still be executing.
  retired: Mutex<Vec<Box<Box<C>>>>,
  // Set once, and never released whilst `self` is alive
  hook: AtomicPtr<Hook>,
  ffi: F,
  // The closures are shared between threads.
  phantom: PhantomData<Box<C>>,
}

impl<F: Copy, C: ?Sized> StaticDetour<F, C> {
  /// Creates the state of a static detour, redirecting to `ffi`.
  ///
  /// # Safety
  ///
  /// `F` must be a function pointer, and `ffi` must invoke the closure using
  /// [`StaticDetour::__with_detour`].
  pub const unsafe fn __new(ffi: F) -> Self {
    StaticDetour {
      closure: AtomicPtr::new(ptr::null_mut()),
      active_calls: AtomicUsize::new(0),
      retired: Mutex::new(Vec::new()),
      hook: AtomicPtr::new(ptr::null_mut()),
      ffi,
      phantom: PhantomData,
    }
  }

  /// Creates the hook of `target`, detoured to `closure`.
  ///
  /// # Safety
  ///
  /// `target` must be a function compatible with `F` (see
  /// [`TypedDetour::new`](crate::TypedDetour::new)).
  pub unsafe fn __initialize(&self, target: F, closure: Box<C>) -> Result<()> {
    if self.hook().is_some() {
      return Err(Error::AlreadyInitialized);
    }

    // SAFETY: The target is compatible with the generated FFI function.
    let hook = unsafe { Hook::new(to_ptr(target), to_ptr(self.ffi))? };
    let hook = Box::into_raw(Box::new(hook));

    // Another thread may have raced to initialize the detour
    let result =
      self
        .hook
        .compare_exchange(ptr::null_mut(), hook, Ordering::AcqRel, Ordering::Acquire);
    if result.is_err() {
      // SAFETY: The hook was never shared.
      drop(unsafe { Box::from_raw(hook) });
      return Err(Error::AlreadyInitialized);
    }
    self.__set_detour(closure);
    Ok(())
  }

  /// Enables the detour.
  ///
  /// # Safety
  ///
  /// See [`TypedDetour::enable`](crate::TypedDetour::enable).
  pub unsafe fn __enable(&self) -> Result<()> {
    let hook = self.hook().ok_or(Error::NotInitialized)?;
    // SAFETY: Forwarded from the caller.
    unsafe { hook.enable() }
  }

  /// Disables the detour.
  ///
  /// # Safety
  ///
  /// See [`TypedDetour::enable`](crate::TypedDetour::enable).
  pub unsafe fn __disable(&self) -> Result<()> {
    let hook = self.hook().ok_or(Error::NotInitialized)?;
    // SAFETY: Forwarded from the caller.
    unsafe { hook.disable() }
  }

  /// Returns whether the detour is enabled or not.
  pub fn __is_enabled(&self) -> bool {
    self.hook().is_some_and(Hook::is_enabled)
  }

  /// Returns the trampoline, or `None` if the detour is not initialized.
  ///
  /// The trampoline is released once `self` is dropped, so this requires a
  /// state that is never dropped.
  pub fn __trampoline(&'static self) -> Option<F> {
    // SAFETY: `F` is a function pointer (see `__new`), sharing the target's
    // signature.
    self.hook().map(|hook| unsafe { from_ptr(hook.trampoline()) })
  }

  /// Returns the trampoline.
  ///
  /// # Panics
  ///
  /// Panics if the detour is not initialized.
  #[track_caller]
  pub fn __original(&'static self) -> F {
    self.__trampoline().expect("static detour is not initialized")
  }

  /// Replaces the detour closure.
  ///
  /// The previous closure may still be executing on another thread (or be the
  /// caller), so it is retired and released once no call is in progress.
  ///
  /// All operations on `closure` and `active_calls` are sequentially
  /// consistent. A call increments `active_calls` before loading `closure`,
  /// so if `active_calls` is observed as zero after a closure was swapped out,
  /// every call that may have loaded it has completed.
  pub fn __set_detour(&self, closure: Box<C>) {
    let previous = self.closure.swap(Box::into_raw(Box::new(closure)), Ordering::SeqCst);

    let released = {
      let mut retired = self.retired.lock();
      if !previous.is_null() {
        // SAFETY: The pointer originates from `Box::into_raw`, and was
        // exclusively obtained by the swap.
        retired.push(unsafe { Box::from_raw(previous) });
      }

      if self.active_calls.load(Ordering::SeqCst) == 0 {
        mem::take(&mut *retired)
      } else {
        Vec::new()
      }
    };

    // Released outside of the lock, in case a closure's destructor calls the
    // detoured function.
    drop(released);
  }

  /// Invokes `call` with the active detour closure.
  ///
  /// # Panics
  ///
  /// Panics if the static detour has not yet been initialized.
  #[inline]
  pub fn __with_detour<R>(&self, call: impl FnOnce(&C) -> R) -> R {
    struct Active<'a>(&'a AtomicUsize);

    impl Drop for Active<'_> {
      fn drop(&mut self) {
        self.0.fetch_sub(1, Ordering::SeqCst);
      }
    }

    self.active_calls.fetch_add(1, Ordering::SeqCst);
    let _active = Active(&self.active_calls);

    // SAFETY: The closure is only released once no call is active (see
    // `__set_detour`), or when `self` is dropped.
    let closure = unsafe { self.closure.load(Ordering::SeqCst).as_ref() }
      .expect("static detour closure is not initialized");
    call(closure)
  }

  /// Returns the hook, if initialized.
  pub(crate) fn hook(&self) -> Option<&Hook> {
    // SAFETY: The pointer is either null, or a hook that is never released
    // whilst `self` is alive.
    unsafe { self.hook.load(Ordering::Acquire).as_ref() }
  }
}

/// Converts a function pointer into an untyped pointer.
fn to_ptr<F: Copy>(function: F) -> *const () {
  const { assert!(mem::size_of::<F>() == mem::size_of::<*const ()>()) };
  // SAFETY: `F` is a function pointer, of the same size as a data pointer.
  unsafe { mem::transmute_copy(&function) }
}

/// Converts an untyped pointer into a function pointer.
///
/// # Safety
///
/// `F` must be a function pointer, compatible with the function at `ptr`.
unsafe fn from_ptr<F: Copy>(ptr: *const ()) -> F {
  const { assert!(mem::size_of::<F>() == mem::size_of::<*const ()>()) };
  // SAFETY: See above.
  unsafe { mem::transmute_copy(&ptr) }
}

impl<F, C: ?Sized> Drop for StaticDetour<F, C> {
  fn drop(&mut self) {
    // The hook is disabled first, so no closure can be executing.
    let hook = *self.hook.get_mut();
    if !hook.is_null() {
      // SAFETY: The hook is exclusively owned by `self`.
      drop(unsafe { Box::from_raw(hook) });
    }

    let closure = *self.closure.get_mut();
    if !closure.is_null() {
      // SAFETY: The closure is exclusively owned by `self`.
      drop(unsafe { Box::from_raw(closure) });
    }
  }
}

impl<F, C: ?Sized> fmt::Debug for StaticDetour<F, C> {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    // SAFETY: See `hook`.
    let hook = unsafe { self.hook.load(Ordering::Acquire).as_ref() };
    f.debug_struct("StaticDetour")
      .field("hook", &hook)
      .finish_non_exhaustive()
  }
}

/// A handle to a [`StaticDetour`], generated by [`static_detour!`].
///
/// # Safety
///
/// `__state` must always return the same detour.
///
/// [`static_detour!`]: crate::static_detour
#[doc(hidden)]
pub unsafe trait StaticHandle: Copy {
  /// The function pointer type.
  type Function: Copy + 'static;
  /// The closure type.
  type Closure: ?Sized + 'static;

  /// Returns the state of the detour.
  fn __state(self) -> &'static StaticDetour<Self::Function, Self::Closure>;
}

impl<H: StaticHandle> crate::transaction::private::Sealed for H {
  fn hook(&self) -> Option<&Hook> {
    self.__state().hook()
  }
}

impl<H: StaticHandle> crate::Detour for H {}

#[cfg(test)]
mod tests {
  use super::*;
  use std::sync::Arc;
  use std::sync::atomic::AtomicBool;
  use std::thread;

  type Closure = dyn Fn(u32) -> u32 + Send + Sync;

  fn original(value: u32) -> u32 {
    value
  }

  /// Counts the number of released closures.
  struct Tracked(Arc<AtomicUsize>);

  impl Drop for Tracked {
    fn drop(&mut self) {
      self.0.fetch_add(1, Ordering::SeqCst);
    }
  }

  fn tracked(value: u32, released: &Arc<AtomicUsize>) -> Box<Closure> {
    let token = Tracked(released.clone());
    Box::new(move |x| {
      let _ = &token;
      x + value
    })
  }

  #[test]
  fn replaced_closures_are_released_when_inactive() {
    // SAFETY: The hook is never created, so the FFI function is never used.
    let detour = unsafe { StaticDetour::<fn(u32) -> u32, Closure>::__new(original) };
    let released = Arc::new(AtomicUsize::new(0));

    detour.__set_detour(tracked(1, &released));
    assert_eq!(detour.__with_detour(|closure| closure(1)), 2);

    detour.__set_detour(tracked(2, &released));
    assert_eq!(released.load(Ordering::SeqCst), 1);

    // A closure replaced whilst executing remains valid until it returns
    detour.__with_detour(|closure| {
      detour.__set_detour(tracked(3, &released));
      assert_eq!(closure(1), 3);
    });
    assert_eq!(released.load(Ordering::SeqCst), 1);
    assert_eq!(detour.__with_detour(|closure| closure(1)), 4);

    // Retired closures are released upon the next inactive replacement
    detour.__set_detour(tracked(4, &released));
    assert_eq!(released.load(Ordering::SeqCst), 3);

    drop(detour);
    assert_eq!(released.load(Ordering::SeqCst), 4);
  }

  #[test]
  fn concurrent_replacement() {
    const REPLACEMENTS: u32 = 1000;

    // SAFETY: The hook is never created, so the FFI function is never used.
    let detour = unsafe { StaticDetour::<fn(u32) -> u32, Closure>::__new(original) };
    let released = Arc::new(AtomicUsize::new(0));
    let done = AtomicBool::new(false);
    detour.__set_detour(tracked(0, &released));

    thread::scope(|scope| {
      for _ in 0..4 {
        scope.spawn(|| {
          while !done.load(Ordering::Relaxed) {
            assert!(detour.__with_detour(|closure| closure(0)) < REPLACEMENTS);
          }
        });
      }

      for value in 1..REPLACEMENTS {
        detour.__set_detour(tracked(value, &released));
      }
      done.store(true, Ordering::Relaxed);
    });

    // All closures but the active one are released once no call is active
    detour.__set_detour(tracked(0, &released));
    assert_eq!(released.load(Ordering::SeqCst), REPLACEMENTS as usize);
  }
}
