(function() {var implementors = {};
implementors["detour"] = ["impl&lt;U&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;U&gt; for UTerm <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Unsigned,&nbsp;</span>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;B0&gt; for UTerm","impl&lt;U, B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;B1&gt; for UInt&lt;U, B&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: Bit,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Unsigned,&nbsp;</span>","impl&lt;U, B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;B0&gt; for UInt&lt;U, B&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: Bit,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Unsigned,&nbsp;</span>","impl&lt;U, B, Ur, Br&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;UInt&lt;Ur, Br&gt;&gt; for UInt&lt;U, B&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: Bit,<br>&nbsp;&nbsp;&nbsp;&nbsp;Br: Bit,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Unsigned + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;&lt;UInt&lt;Ur, Br&gt; as <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html\" title=\"trait core::ops::Sub\">Sub</a>&lt;B1&gt;&gt;::<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html\" title=\"trait core::ops::Sub\">Output</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;Ur: Unsigned,<br>&nbsp;&nbsp;&nbsp;&nbsp;UInt&lt;Ur, Br&gt;: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html\" title=\"trait core::ops::Sub\">Sub</a>&lt;B1&gt;,&nbsp;</span>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;B1&gt; for UTerm","impl&lt;U, B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Shr.html\" title=\"trait core::ops::Shr\">Shr</a>&lt;UTerm&gt; for UInt&lt;U, B&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: Bit,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Unsigned,&nbsp;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
