//! Example of code generated by a static detour. **IT MUST NOT BE USED OUTSIDE
//! THIS CRATE**.
//!
//! ```c
//! static_detours! {
//!     pub struct Detour: extern "system" fn(i32, String, bool) -> f32;
//! }
//! ```

static_detours! {
    pub struct Static: extern "system" fn(i32, String, bool) -> f32;
}
