//! Example of code generated by the macro. **IT MUST NOT BE USED OUTSIDE
//! THIS CRATE**.
//!
//! ```c
//! static_detours! {
//!     pub struct Detour: extern "system" fn(i32, String, bool) -> f32;
//! }
//! ```

static_detours! {
    pub struct Detour: extern "system" fn(i32, String, bool) -> f32;
}
